### ISSUE TITLE
Provide the Tab button on the UI

### ISSUE THREAD

**Issue by alanjds** [FoamyGuy/Android_CircuitPython_Editor#1]
Most Android serial "emulators"/clients does not have the Tab button available. This is VERY useful for the code completion.

Please include it along the Ctrl modifiers.

**Comment by FoamyGuy** [comment]
> This is VERY useful for the code completion.

When you say 'code completion' do you mean something like intellisense where you can type only part of the thing you need and then press [TAB] it will suggest the most likely things based on what you've typed so far?

I can add the [TAB] button in the UI but I don't think it will work for auto-completion like this by default, that behavior would have to built up a bit in the Java app in order to work I believe.

**Comment by alanjds** [comment]
Well, on the Micropython REPL it introspects the possibilities and provide what exists.

I tried to use Termux + minicom/picocom, but seems to have not access to the Android serial port. On a real computer it works like a charm

**Comment by FoamyGuy** [comment]
That is amazing! I had no idea that it had the completion built in like that. I've added a tab button and it can suggest things back. The behavior is a little messed up so I need to tweak it a bit but I think it will be possible to get it working correctly.

Thank you for opening this issue.

**Comment by alanjds** [comment]
Happy to be helpful.

If you can, please release an APK after merging the TAB.

Thank you for providing a serial terminal specific for Python-based boards.

**Comment by FoamyGuy** [comment]
The TAB button APK file is checked in now. It's working for somethings but not quite perfect, feel free to open new issues if you spot bad behavior.
